
//! Autogenerated weights for `pallet_offences`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-02-01, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `MACs-MacBook-Air.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/serv-node
// benchmark
// pallet
// --chain
// dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_offences
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/pallet_offences.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_offences`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_offences::WeightInfo for WeightInfo<T> {
	// Storage: Offences ReportsByKindIndex (r:1 w:1)
	// Storage: Offences ConcurrentReportsIndex (r:1 w:1)
	// Storage: Offences Reports (r:100 w:100)
	// Storage: Staking SlashRewardFraction (r:1 w:0)
	// Storage: Staking ActiveEra (r:1 w:0)
	// Storage: Staking ErasStartSessionIndex (r:1 w:0)
	// Storage: Staking Invulnerables (r:1 w:0)
	// Storage: Staking ValidatorSlashInEra (r:100 w:100)
	// Storage: Staking SlashingSpans (r:1700 w:1700)
	// Storage: Staking SpanSlash (r:1700 w:1700)
	// Storage: Staking Validators (r:100 w:100)
	// Storage: Staking CounterForValidators (r:1 w:1)
	// Storage: VoterList ListNodes (r:292 w:292)
	// Storage: VoterList ListBags (r:7 w:7)
	// Storage: VoterList CounterForListNodes (r:1 w:1)
	// Storage: Staking Nominators (r:100 w:0)
	// Storage: Staking OffendingValidators (r:1 w:1)
	// Storage: Session Validators (r:1 w:0)
	// Storage: Staking NominatorSlashInEra (r:1600 w:1600)
	// Storage: Staking UnappliedSlashes (r:1 w:1)
	/// The range of component `r` is `[1, 100]`.
	/// The range of component `o` is `[2, 100]`.
	/// The range of component `n` is `[0, 16]`.
	fn report_offence_im_online(r: u32, o: u32, n: u32, ) -> Weight {
		// Minimum execution time: 617_000 nanoseconds.
		Weight::from_ref_time(621_000_000 as u64)
			// Standard Error: 4_488_137
			.saturating_add(Weight::from_ref_time(19_257_382 as u64).saturating_mul(r as u64))
			// Standard Error: 4_512_541
			.saturating_add(Weight::from_ref_time(290_591_336 as u64).saturating_mul(o as u64))
			// Standard Error: 27_420_226
			.saturating_add(Weight::from_ref_time(230_214_171 as u64).saturating_mul(n as u64))
			.saturating_add(T::DbWeight::get().reads(124 as u64))
			.saturating_add(T::DbWeight::get().reads((37 as u64).saturating_mul(o as u64)))
			.saturating_add(T::DbWeight::get().reads((187 as u64).saturating_mul(n as u64)))
			.saturating_add(T::DbWeight::get().writes(117 as u64))
			.saturating_add(T::DbWeight::get().writes((36 as u64).saturating_mul(o as u64)))
			.saturating_add(T::DbWeight::get().writes((187 as u64).saturating_mul(n as u64)))
	}
	// Storage: Offences ReportsByKindIndex (r:1 w:1)
	// Storage: Offences ConcurrentReportsIndex (r:1 w:1)
	// Storage: Offences Reports (r:1 w:1)
	// Storage: Staking SlashRewardFraction (r:1 w:0)
	// Storage: Staking ActiveEra (r:1 w:0)
	// Storage: Staking ErasStartSessionIndex (r:1 w:0)
	// Storage: Staking Invulnerables (r:1 w:0)
	// Storage: Staking ValidatorSlashInEra (r:1 w:1)
	// Storage: Staking SlashingSpans (r:1 w:1)
	// Storage: Staking SpanSlash (r:1 w:1)
	// Storage: Staking Validators (r:1 w:1)
	// Storage: Staking CounterForValidators (r:1 w:1)
	// Storage: VoterList ListNodes (r:1 w:1)
	// Storage: VoterList ListBags (r:1 w:1)
	// Storage: VoterList CounterForListNodes (r:1 w:1)
	// Storage: Staking Nominators (r:1 w:0)
	// Storage: Staking OffendingValidators (r:1 w:1)
	// Storage: Session Validators (r:1 w:0)
	// Storage: Staking UnappliedSlashes (r:1 w:1)
	// Storage: Staking NominatorSlashInEra (r:1 w:1)
	/// The range of component `n` is `[0, 16]`.
	fn report_offence_grandpa(n: u32, ) -> Weight {
		// Minimum execution time: 147_000 nanoseconds.
		Weight::from_ref_time(171_165_867 as u64)
			// Standard Error: 134_444
			.saturating_add(Weight::from_ref_time(15_818_368 as u64).saturating_mul(n as u64))
			.saturating_add(T::DbWeight::get().reads(20 as u64))
			.saturating_add(T::DbWeight::get().reads((3 as u64).saturating_mul(n as u64)))
			.saturating_add(T::DbWeight::get().writes(14 as u64))
			.saturating_add(T::DbWeight::get().writes((3 as u64).saturating_mul(n as u64)))
	}
	// Storage: Offences ReportsByKindIndex (r:1 w:1)
	// Storage: Offences ConcurrentReportsIndex (r:1 w:1)
	// Storage: Offences Reports (r:1 w:1)
	// Storage: Staking SlashRewardFraction (r:1 w:0)
	// Storage: Staking ActiveEra (r:1 w:0)
	// Storage: Staking ErasStartSessionIndex (r:1 w:0)
	// Storage: Staking Invulnerables (r:1 w:0)
	// Storage: Staking ValidatorSlashInEra (r:1 w:1)
	// Storage: Staking SlashingSpans (r:1 w:1)
	// Storage: Staking SpanSlash (r:1 w:1)
	// Storage: Staking Validators (r:1 w:1)
	// Storage: Staking CounterForValidators (r:1 w:1)
	// Storage: VoterList ListNodes (r:1 w:1)
	// Storage: VoterList ListBags (r:1 w:1)
	// Storage: VoterList CounterForListNodes (r:1 w:1)
	// Storage: Staking Nominators (r:1 w:0)
	// Storage: Staking OffendingValidators (r:1 w:1)
	// Storage: Session Validators (r:1 w:0)
	// Storage: Staking UnappliedSlashes (r:1 w:1)
	// Storage: Staking NominatorSlashInEra (r:1 w:1)
	/// The range of component `n` is `[0, 16]`.
	fn report_offence_babe(n: u32, ) -> Weight {
		// Minimum execution time: 140_000 nanoseconds.
		Weight::from_ref_time(178_969_462 as u64)
			// Standard Error: 149_164
			.saturating_add(Weight::from_ref_time(15_660_709 as u64).saturating_mul(n as u64))
			.saturating_add(T::DbWeight::get().reads(20 as u64))
			.saturating_add(T::DbWeight::get().reads((3 as u64).saturating_mul(n as u64)))
			.saturating_add(T::DbWeight::get().writes(14 as u64))
			.saturating_add(T::DbWeight::get().writes((3 as u64).saturating_mul(n as u64)))
	}
}
